[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.29"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"

[etherscan]
hedera_testnet = { key = "${HEDERA_EXPLORER_API_KEY}", url = "https://testnet.hashscan.io" }
hedera_mainnet = { key = "${HEDERA_EXPLORER_API_KEY}", url = "https://hashscan.io" }
